# Site settings
title: Ann John
header-img: img/home-bg.png
email: ann@flatironschool.com
copyright_name: AnnJohn
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: @anniesaysthat
github_username:  AnnJohn
learn_profile: AnnJohn
email_username: ann@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
